version: '3.7'
services:
  jenkins:
    image: techyogi2/jenkins:debian
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false -Dhudson.footerURL=http://www.example.com
    ports:
      - 80:8080
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
     
volumes:
  jenkins_data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/admin/jenkinsdata"